let v1,v2,v3,v4
v1=10 
v2="10"
v3=v1===v2
v4={nome:'Bruno'}

// é tudo diferente no typo

console.log("Valor: "+ v1 + " - Tipo: " + typeof(V )let v1,v2,v3,v4
v1=10 
v2="10"
v3=v1===v2
v4={nome:'Bruno'}

// é tudo diferente no typo

console.log(v1)
console.log(v2)
console.log(v3)
console.log(v4)
console.log("Valor: "+ v3 + " - Tipo: " + typeof(V )
console.log("Valor: "+ v4 + " - Tipo: " + typeof(V )